import React, { useState } from 'react';

export const DatabaseSetupGuide: React.FC = () => {
  const [isOpen, setIsOpen] = useState(false);

  const step1Sql = `
-- ⚠️ 第一步：建立表格 (RUN 运行一次即可)

drop table if exists records;
drop table if exists users;

-- 1. 创建记录表
create table records (
  id bigint generated by default as identity primary key,
  user_name text not null,
  prize_name text not null,
  prize_type text not null,
  prize_value int default 0,
  is_redeemed boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. 创建用户表 (设置 name 为唯一，防止同一个人有两个账号)
create table users (
  id bigint generated by default as identity primary key,
  name text not null,
  points int default 0, 
  fragment_500 int default 0,
  fragment_free int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique(name)
);

-- 3. 开启权限 (允许所有读写，简单粗暴)
alter table records enable row level security;
create policy "Allow all access" on records for all using (true) with check (true);

alter table users enable row level security;
create policy "Allow all access" on users for all using (true) with check (true);
  `;

  const step2Sql = `
-- ⚠️ 第二步：导入学员积分数据
-- 请将下面的 ('姓名', 积分) 替换为您 Excel 里的真实数据
-- 注意：最后一个不用加逗号，前面的每行都要加逗号

insert into users (name, points) values 
  ('张三', 300),
  ('李四', 60),
  ('王五', 1500),
  ('陈六', 30)
on conflict (name) do update 
set points = excluded.points;

-- 点击 RUN 之后，这些用户就进去了
  `;

  if (!isOpen) {
    return (
      <button 
        onClick={() => setIsOpen(true)}
        className="fixed bottom-4 right-4 bg-red-600 text-white px-4 py-2 rounded-full shadow-lg z-50 text-sm animate-bounce font-bold border-2 border-white"
      >
        🆘 必看：数据库安装指南
      </button>
    );
  }

  return (
    <div className="fixed inset-0 bg-black/95 z-50 overflow-y-auto p-4 flex items-center justify-center">
      <div className="bg-gray-900 text-white rounded-xl border border-gray-700 p-6 max-w-3xl w-full shadow-2xl">
        <div className="flex justify-between items-center mb-6 border-b border-gray-700 pb-4">
            <h2 className="text-2xl font-bold text-epe-blue">🚀 数据库设置向导 (分两步走)</h2>
            <button onClick={() => setIsOpen(false)} className="text-gray-400 hover:text-white">✕</button>
        </div>
        
        <div className="space-y-8">
            {/* Step 1 */}
            <div>
                <div className="flex items-center gap-2 mb-2">
                    <span className="bg-epe-blue text-black font-bold px-2 py-1 rounded text-sm">步骤 1</span>
                    <h3 className="font-bold text-lg">建立表格结构</h3>
                </div>
                <p className="text-sm text-gray-400 mb-2">将这段代码复制到 Supabase SQL Editor 并点击 <strong className="text-green-400">Run</strong>。</p>
                <div className="relative">
                    <textarea readOnly className="w-full h-32 bg-black border border-gray-700 text-green-400 p-3 text-xs font-mono rounded" value={step1Sql.trim()} />
                    <button 
                        onClick={() => navigator.clipboard.writeText(step1Sql.trim())}
                        className="absolute top-2 right-2 bg-gray-700 hover:bg-gray-600 text-white px-2 py-1 text-xs rounded transition"
                    >
                        复制 Step 1 代码
                    </button>
                </div>
            </div>

            {/* Step 2 */}
            <div>
                <div className="flex items-center gap-2 mb-2">
                    <span className="bg-epe-purple text-white font-bold px-2 py-1 rounded text-sm">步骤 2</span>
                    <h3 className="font-bold text-lg">批量导入学员名单</h3>
                </div>
                <p className="text-sm text-gray-400 mb-2">
                    1. 将您的 Excel 表格整理成 <code className="text-yellow-400">('姓名', 积分),</code> 的格式。<br/>
                    2. 替换下面的 values 部分。<br/>
                    3. 运行代码。这样所有学员的数据就一次性进去了。
                </p>
                <div className="relative">
                    <textarea readOnly className="w-full h-40 bg-black border border-gray-700 text-purple-300 p-3 text-xs font-mono rounded" value={step2Sql.trim()} />
                    <button 
                        onClick={() => navigator.clipboard.writeText(step2Sql.trim())}
                        className="absolute top-2 right-2 bg-gray-700 hover:bg-gray-600 text-white px-2 py-1 text-xs rounded transition"
                    >
                        复制 Step 2 模板
                    </button>
                </div>
            </div>
        </div>

        <div className="mt-8 pt-4 border-t border-gray-700 flex justify-end">
            <button 
                onClick={() => setIsOpen(false)}
                className="bg-epe-blue hover:bg-cyan-400 text-black font-bold py-2 px-6 rounded-lg transition"
            >
                明白了，去操作
            </button>
        </div>
      </div>
    </div>
  );
};